src/Barebone/ViewModels/Shared/Menu/MenuViewModel.cs
// Copyright © 2017 Dmitry Sikorsky. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System.Collections.Generic;

namespace Barebone.ViewModels.Shared
{
  public class MenuViewModel
  {
    public IEnumerable<MenuItemViewModel> MenuItems { get; set; }
  }
}

src/Barebone/ViewModels/Shared/Menu/MenuViewModelFactory.cs
// Copyright © 2017 Dmitry Sikorsky. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using ExtCore.Infrastructure;
using Infrastructure;
using System.Collections.Generic;
using System.Linq;

namespace Barebone.ViewModels.Shared
{
  public class MenuViewModelFactory
  {
    public MenuViewModel Create()
    {
      List<MenuItem> menuItems = new List<MenuItem>();

      foreach (IExtensionMetadata extensionMetadata in ExtensionManager.GetInstances<IExtensionMetadata>())
        menuItems.AddRange(extensionMetadata.MenuItems);

      return new MenuViewModel()
      {
        MenuItems = menuItems.OrderBy(mi => mi.Position).Select(
          mi => new MenuItemViewModelFactory().Create(mi)
        )
      };
    }
  }
}

src/Barebone/ViewModels/Shared/MenuItem/MenuItemViewModel.cs
// Copyright © 2017 Dmitry Sikorsky. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

namespace Barebone.ViewModels.Shared
{
  public class MenuItemViewModel
  {
    public string Url { get; set; }
    public string Name { get; set; }
  }
}

src/Barebone/ViewModels/Shared/MenuItem/MenuItemViewModelFactory.cs
// Copyright © 2017 Dmitry Sikorsky. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using Infrastructure;

namespace Barebone.ViewModels.Shared
{
  public class MenuItemViewModelFactory
  {
    public MenuItemViewModel Create(MenuItem menuItem)
    {
      return new MenuItemViewModel()
      {
        Url = menuItem.Url,
        Name = menuItem.Name
      };
    }
  }
}

src/Barebone/ViewModels/Shared/Script/ScriptViewModel.cs
// Copyright © 2017 Dmitry Sikorsky. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

namespace Barebone.ViewModels.Shared
{
  public class ScriptViewModel
  {
    public string Url { get; set; }
  }
}

src/Barebone/ViewModels/Shared/Script/ScriptViewModelFactory.cs
// Copyright © 2017 Dmitry Sikorsky. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using Infrastructure;

namespace Barebone.ViewModels.Shared
{
  public class ScriptViewModelFactory
  {
    public ScriptViewModel Create(Script script)
    {
      return new ScriptViewModel()
      {
        Url = script.Url
      };
    }
  }
}

src/Barebone/ViewModels/Shared/Scripts/ScriptsViewModel.cs
// Copyright © 2017 Dmitry Sikorsky. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System.Collections.Generic;

namespace Barebone.ViewModels.Shared
{
  public class ScriptsViewModel
  {
    public IEnumerable<ScriptViewModel> Scripts { get; set; }
  }
}

src/Barebone/ViewModels/Shared/Scripts/ScriptsViewModelFactory.cs
// Copyright © 2017 Dmitry Sikorsky. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using ExtCore.Infrastructure;
using Infrastructure;
using System.Collections.Generic;
using System.Linq;

namespace Barebone.ViewModels.Shared
{
  public class ScriptsViewModelFactory
  {
    public ScriptsViewModel Create()
    {
      List<Script> scripts = new List<Script>();

      foreach (IExtensionMetadata extensionMetadata in ExtensionManager.GetInstances<IExtensionMetadata>())
        scripts.AddRange(extensionMetadata.Scripts);

      return new ScriptsViewModel()
      {
        Scripts = scripts.OrderBy(s => s.Position).Select(
          s => new ScriptViewModelFactory().Create(s)
        )
      };
    }
  }
}

src/Barebone/ViewModels/Shared/StyleSheet/StyleSheetViewModel.cs
// Copyright © 2017 Dmitry Sikorsky. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

namespace Barebone.ViewModels.Shared
{
  public class StyleSheetViewModel
  {
    public string Url { get; set; }
  }
}

src/Barebone/ViewModels/Shared/StyleSheet/StyleSheetViewModelFactory.cs
// Copyright © 2017 Dmitry Sikorsky. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using Infrastructure;

namespace Barebone.ViewModels.Shared
{
  public class StyleSheetViewModelFactory
  {
    public StyleSheetViewModel Create(StyleSheet styleSheet)
    {
      return new StyleSheetViewModel()
      {
        Url = styleSheet.Url
      };
    }
  }
}

src/Barebone/ViewModels/Shared/StyleSheets/StyleSheetsViewModel.cs
// Copyright © 2017 Dmitry Sikorsky. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System.Collections.Generic;

namespace Barebone.ViewModels.Shared
{
  public class StyleSheetsViewModel
  {
    public IEnumerable<StyleSheetViewModel> StyleSheets { get; set; }
  }
}

src/Barebone/ViewModels/Shared/StyleSheets/StyleSheetsViewModelFactory.cs
// Copyright © 2017 Dmitry Sikorsky. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using ExtCore.Infrastructure;
using Infrastructure;
using System.Collections.Generic;
using System.Linq;

namespace Barebone.ViewModels.Shared
{
  public class StyleSheetsViewModelFactory
  {
    public StyleSheetsViewModel Create()
    {
      List<StyleSheet> styleSheets = new List<StyleSheet>();

      foreach (IExtensionMetadata extensionMetadata in ExtensionManager.GetInstances<IExtensionMetadata>())
        styleSheets.AddRange(extensionMetadata.StyleSheets);

      return new StyleSheetsViewModel()
      {
        StyleSheets = styleSheets.OrderBy(ss => ss.Position).Select(
          ss => new StyleSheetViewModelFactory().Create(ss)
        )
      };
    }
  }
}

src/Barebone/ViewComponents/MenuViewComponent.cs
// Copyright © 2017 Dmitry Sikorsky. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using Barebone.ViewModels.Shared;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Barebone.ViewComponents
{
  public class MenuViewComponent : ViewComponent
  {
    public async Task<IViewComponentResult> InvokeAsync()
    {
      return this.View(new MenuViewModelFactory().Create());
    }
  }
}

src/Barebone/ViewComponents/ScriptsViewComponent.cs
// Copyright © 2017 Dmitry Sikorsky. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using Barebone.ViewModels.Shared;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Barebone.ViewComponents
{
  public class ScriptsViewComponent : ViewComponent
  {
    public async Task<IViewComponentResult> InvokeAsync()
    {
      return this.View(new ScriptsViewModelFactory().Create());
    }
  }
}

src/Barebone/ViewComponents/StyleSheetsViewComponent.cs
// Copyright © 2017 Dmitry Sikorsky. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using Barebone.ViewModels.Shared;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Barebone.ViewComponents
{
  public class StyleSheetsViewComponent : ViewComponent
  {
    public async Task<IViewComponentResult> InvokeAsync()
    {
      return this.View(new StyleSheetsViewModelFactory().Create());
    }
  }
}

src/Barebone/Views/Shared/_Layout.cshtml
@* Copyright © 2017 Dmitry Sikorsky. All rights reserved. *@
@* Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information. *@
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>@Html.Raw(this.ViewBag.Title as string)</title>
  @await Component.InvokeAsync("StyleSheets")
  @await Component.InvokeAsync("Scripts")
</head>
<body>
  <div class="master-detail-view">
    <div class="master-detail-view__master">
      <h1 class="master-detail-view__title">
        Demo
      </h1>
      @await Component.InvokeAsync("Menu")
    </div>
    <div class="master-detail-view__detail">
      @RenderBody()
    </div>
  </div>
</body>
</html>

src/Barebone/Views/Shared/_Menu.cshtml
@* Copyright © 2017 Dmitry Sikorsky. All rights reserved. *@
@* Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information. *@
@model Barebone.ViewModels.Shared.MenuViewModel
<div class="master-detail-view__menu menu">
  @foreach (var menuItem in this.Model.MenuItems)
  {
    @Html.Partial("_MenuItem", menuItem)
  }
</div>

src/Barebone/Views/Shared/_MenuItem.cshtml
@* Copyright © 2017 Dmitry Sikorsky. All rights reserved. *@
@* Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information. *@
@model Barebone.ViewModels.Shared.MenuItemViewModel
<a class="menu__item" href="@Model.Url">
  @Model.Name
</a>

src/Barebone/Views/Shared/_Script.cshtml
@* Copyright © 2017 Dmitry Sikorsky. All rights reserved. *@
@* Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information. *@
@model Barebone.ViewModels.Shared.ScriptViewModel
<script src="@Model.Url"></script>

src/Barebone/Views/Shared/_Scripts.cshtml
@* Copyright © 2017 Dmitry Sikorsky. All rights reserved. *@
@* Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information. *@
@model Barebone.ViewModels.Shared.ScriptsViewModel
@foreach (var script in this.Model.Scripts)
{
  @Html.Partial("_Script", script)
}

src/Barebone/Views/Shared/_StyleSheet.cshtml
@* Copyright © 2017 Dmitry Sikorsky. All rights reserved. *@
@* Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information. *@
@model Barebone.ViewModels.Shared.StyleSheetViewModel
<link href="@Model.Url" rel="stylesheet">

src/Barebone/Views/Shared/_StyleSheets.cshtml
@* Copyright © 2017 Dmitry Sikorsky. All rights reserved. *@
@* Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information. *@
@model Barebone.ViewModels.Shared.StyleSheetsViewModel
@foreach (var styleSheet in this.Model.StyleSheets)
{
  @Html.Partial("_StyleSheet", styleSheet)
}